export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER_DETAIL = 'FETCH_USER_DETAIL';
export const FETCH_BOOK_RECORD = 'FETCH_BOOK_RECORD';

export const SHOW_BOOK_MODAL = 'SHOW_BOOK_MODAL';
export const HIDE_BOOK_MODAL = 'HIDE_BOOK_MODAL';

export const TOGGLE_CREATE_USER_MODAL = 'TOGGLE_CREATE_USER_MODAL';

export const TOGGLE_DELETE_USER_MODAL = 'TOGGLE_DELETE_USER_MODAL';